services:
    backend:
        build: 
            context: ./backend
        env_file:
            - ./backend/.env
        ports:
            - '3000:3000'
        environment:
            DB_HOST: database
        depends_on:
            database:
                condition: service_healthy

    frontend:
        build: 
            context: ./frontend
        ports:
            - '5173:5173'
        depends_on:
            - backend
    database:
        image: postgres:17
        ports: 
            - '5432:5432'
        environment:
            POSTGRES_DB: expense_tracker
            POSTGRES_USER: Moses
            POSTGRES_PASSWORD: "password"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U Moses -d expense_tracker"]
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    postgres_data: